services:
  postgres:
    image: postgres:16.2
    container_name: form-maker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 715905854476
      POSTGRES_DB: main
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  form-maker: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: form-maker-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
