import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Toaster } from 'react-hot-toast'

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Form Builder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} bg-main-background grid grid-rows-[104px_1fr] antialiased`}
      >
        <Toaster
          position="bottom-center"
          toastOptions={{
            success: {
              style: {
                background: '#12B76A',
                color: '#fff',
                fontWeight: 500,
                fontSize: '1.125rem',
                maxWidth: '40%',
              },
              iconTheme: {
                primary: '#027A48',
                secondary: '#fff',
              },
            },
            error: {
              style: {
                background: '#F04438',
                color: '#fff',
                fontWeight: 500,
                fontSize: '1.125rem',
                maxWidth: '40%',
              },
              iconTheme: {
                primary: '#B42318',
                secondary: '#fff',
              },
            },
          }}
        />
        <Header />
        <div />
        <main className="px-4 lg:px-20">{children}</main>
      </body>
    </html>
  )
}
